---
output_dir: output
data_sources:
- type: filesystem_unified
  items_root: /
  layouts_root: /
  
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'textile', 'txt', 'xhtml', 'xml' ]
index_filenames: [ 'index.html' ]

twitter_username: meineerde

# disabled for now
#disqus_shortname: meineerde